# Generated by Django 2.2.12 on 2021-02-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('example', models.ImageField(upload_to='', verbose_name='代码截图')),
                ('dataType', models.CharField(max_length=32, verbose_name='类别')),
                ('keyWord', models.CharField(max_length=128, verbose_name='关键字')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('keep_one', models.CharField(default=None, max_length=256, verbose_name='保留字段1')),
                ('keep_two', models.CharField(default=None, max_length=256, verbose_name='保留字段2')),
                ('keep_three', models.IntegerField(verbose_name='保留字段3')),
                ('keep_four', models.IntegerField(verbose_name='保留字段4')),
            ],
            options={
                'verbose_name': '数据成员表',
                'verbose_name_plural': '数据成员表',
                'ordering': ['id'],
            },
        ),
    ]
