# Generated by Django 2.2.12 on 2021-02-27 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datamembers',
            name='code',
            field=models.TextField(default=None, verbose_name='代码'),
        ),
    ]
