# Generated by Django 2.2.12 on 2021-02-27 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesdata', '0002_datamembers_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamembers',
            name='example',
            field=models.ImageField(null=True, upload_to='', verbose_name='代码截图'),
        ),
        migrations.AlterField(
            model_name='datamembers',
            name='keep_four',
            field=models.IntegerField(null=True, verbose_name='保留字段4'),
        ),
        migrations.AlterField(
            model_name='datamembers',
            name='keep_three',
            field=models.IntegerField(null=True, verbose_name='保留字段3'),
        ),
    ]
