# Generated by Django 2.2.12 on 2021-03-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesdata', '0003_auto_20210227_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamembers',
            name='keep_one',
            field=models.CharField(default='0', max_length=256, verbose_name='保留字段1'),
        ),
        migrations.AlterField(
            model_name='datamembers',
            name='keep_two',
            field=models.CharField(default='0', max_length=256, verbose_name='保留字段2'),
        ),
    ]
